

ALTER TABLE `t_couns_details` CHANGE `Couns_REMARKS` `Couns_REMARKS` VARCHAR(50) NULL;

ALTER TABLE `t_counseling` ADD `Couns_RECOMMENDATION` TEXT DEFAULT NULL AFTER `Couns_COMMENT`;

ALTER TABLE `t_upload` ADD `Upload_TYPE` VARCHAR(15) NOT NULL AFTER `Upload_CATEGORY`;

ALTER TABLE `r_upload_category` ADD `Upload_CATEGORY_ID` INT NOT NULL AUTO_INCREMENT FIRST, ADD `Upload_CATEGORY_STAT` ENUM('Active','Inactive') NULL DEFAULT 'Active' AFTER `Upload_FILE_CATEGORY`, ADD PRIMARY KEY (`Upload_CATEGORY_ID`);